---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-flow
# description will be included in the image's metadata
description: Custom image for Asus R.O.G. Flow Z13 (2025)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
      copr:
        - atim/starship
        - lukenukem/asus-linux/
    install:
      packages:
        - code
        - containerd.io
        - docker-buildx-plugin
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - docker-model-plugin
        - adcli
        - adw-gtk3-theme
        - adwaita-fonts-all
        - android-tools
        - asusctl
        - bash-color-prompt
        - bcache-tools
        - bcc
        - bootc
        - bpftop
        - bpftrace
        - cascadia-code-fonts
        - cockpit-bridge
        - cockpit-machines
        - cockpit-networkmanager
        - cockpit-ostree
        - cockpit-podman
        - cockpit-selinux
        - cockpit-storaged
        - cockpit-system
        - containerd
        - cryfs
        - davfs2
        - dbus-x11
        - ddcutil
        - edk2-ovmf
        - evtest
        - fastfetch
        - firewall-config
        - fish
        - flatpak-builder
        - foo2zjs
        - fuse-encfs
        - gcc
        - genisoimage
        - git-credential-libsecret
        - git-subtree
        - git-svn
        - glow
        - gnome-tweaks
        - gum
        - hplip
        - ibus-mozc
        - ifuse
        - incus
        - incus-agent
        - input-remapper
        - iotop
        - iwd
        - jetbrains-mono-fonts-all
        - just
        - krb5-workstation
        - libgda
        - libgda-sqlite
        - libimobiledevice
        - libratbag-ratbagd
        - libsss_autofs
        - libvirt
        - libvirt-nss
        - libxcrypt-compat
        - lm_sensors
        - lxc
        - make
        - mesa-libGLU
        - mozc
        - nautilus-gsconnect
        - nicstat
        - numactl
        - oddjob-mkhomedir
        - opendyslexic-fonts
        - openssh-askpass
        - osbuild-selinux
        - p7zip
        - p7zip-plugins
        - podman-compose
        - podman-machine
        - podman-tui
        - powerstat
        - powertop
        - printer-driver-brlaser
        - pulseaudio-utils
        - python3-pip
        - python3-pygit2
        - qemu
        - qemu-char-spice
        - qemu-device-display-virtio-gpu
        - qemu-device-display-virtio-vga
        - qemu-device-usb-redirect
        - qemu-img
        - qemu-system-x86-core
        - qemu-user-binfmt
        - qemu-user-static
        - rclone
        - restic
        - rocm-hip
        - rocm-opencl
        - rocm-smi
        - samba
        - samba-dcerpc
        - samba-ldb-ldap-modules
        - samba-winbind-clients
        - samba-winbind-modules
        - setools-console
        - sysprof
        - tiptop
        - tmux
        - trace-cmd
        - udica
        - usbip
        - usbmuxd
        - util-linux-script
        - virt-manager
        - virt-v2v
        - virt-viewer
        - waypipe
        - wireguard-tools
        - wl-clipboard
        - xdg-terminal-exec
        - xprop
        - ydotool
        - zenity
        - zsh
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.zulip.Zulip
          - de.gonicus.gonnect
          - im.riot.Riot
          - org.chromium.Chromium
          - com.spotify.Client
          - com.teamspeak.TeamSpeak3
          - com.discordapp.Discord
          - org.mozilla.Thunderbird
          - com.bitwarden.desktop
          - com.moonlight_stream.Moonlight
          - org.videolan.VLC
      - scope: user
  - type: systemd
    enabled:
      - docker.socket
      - podman.socket
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

