---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: AtomicFlow
# description will be included in the image's metadata
description: Custom image for Asus R.O.G. Flow Z13 (2025)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - micro
        - starship

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.zulip.Zulip
          - de.gonicus.gonnect
          - im.riot.Riot
          - org.chromium.Chromium
          - com.spotify.Client
          - com.teamspeak.TeamSpeak3
          - com.discordapp.Discord
          - org.mozilla.Thunderbird
          - com.bitwarden.desktop
          - com.moonlight_stream.Moonlight
          - org.videolan.VLC
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
